# Generated by Django 4.2.16 on 2025-01-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0013_alter_subclip_options_alter_textfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subclip',
            options={},
        ),
        migrations.RemoveField(
            model_name='subclip',
            name='position_in_slide',
        ),
    ]
