# Generated by Django 4.2.16 on 2025-02-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0015_alter_subclip_options_subclip_position_in_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textlinevideoclip',
            options={'ordering': ['position', 'line_number', 'text_file']},
        ),
        migrations.AddField(
            model_name='textlinevideoclip',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
