# Generated by Django 4.2.16 on 2025-02-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0016_alter_textlinevideoclip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='box_radius',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='textfile',
            name='subtitle_opacity',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
