# Generated by Django 4.2.16 on 2025-02-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0017_textfile_box_radius_textfile_subtitle_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='box_radius',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
