# Generated by Django 4.2.16 on 2025-02-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0018_alter_textfile_box_radius'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textlinevideoclip',
            options={'ordering': ['position', 'text_file']},
        ),
        migrations.AlterUniqueTogether(
            name='textlinevideoclip',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='textlinevideoclip',
            name='line_number',
        ),
    ]
