# Generated by Django 4.2.16 on 2025-02-17 08:12

from django.db import migrations, models
import mainapps.vidoe_text.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0019_alter_textlinevideoclip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclip',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='subclips/processed_videos'),
        ),
        migrations.AlterField(
            model_name='subclip',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=mainapps.vidoe_text.models.text_clip_upload_path),
        ),
    ]
