# Generated by Django 4.2.16 on 2025-02-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0020_subclip_processed_video_alter_subclip_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlinevideoclip',
            name='subtitled_clip',
            field=models.FileField(blank=True, null=True, upload_to='subtitled_clips/'),
        ),
    ]
