# Generated by Django 4.2.16 on 2025-03-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0022_subclip_is_tiktok'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textlinevideoclip',
            options={'ordering': ['text_file', 'position']},
        ),
    ]
