# Generated by Django 4.2.16 on 2025-01-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subscription_current_period_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['id']},
        ),
    ]
